### ISSUE TITLE
运行中出现的错误，望解答

### ISSUE THREAD

**Issue by lzzlxxlsz** [oyxhust/wgan-gp-anomaly#5]
你好，想问一下，在我的电脑上一运行就会出现requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=8097): Max retries exceeded with url: /events (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f152aa23048>: Failed to establish a new connection: [Errno 111] Connection refused',))
老是停不下来，您知道这是怎么回事吗，还有一个问题就是会出现这个UnboundLocalError: local variable 'real_data' referenced before assignment，我把它用全局变量定义了一下，但是又会报错real_data没有定义，您知道是什me原因呢

**Comment by oyxhust** [comment]
需要运行visdom

**Comment by lzzlxxlsz** [comment]
这两个问题都是由于没有运行visdom吗

**Comment by oyxhust** [comment]
是的，运行一下visdom

**Comment by lzzlxxlsz** [comment]
您好，我运行了一下visdom，但是还是会报错，'real_data' referenced before assignment还是这个错误

**Comment by oyxhust** [comment]
Please give the detailed error information, like the line number, your environments.

**Comment by lzzlxxlsz** [comment]
WARNING:root:Setting up a new session...
create web directory ./checkpoints\data\web...
Traceback (most recent call last):
  File "E:/果冻/模型/wgan-gp-anomaly-master/wgan-gp-anomaly-master/train.py", line 36, in <module>
    model.optimize_parameters(only_update_D)
  File "E:\果冻\模型\wgan-gp-anomaly-master\wgan-gp-anomaly-master\models\wgan_gp_model.py", line 154, in optimize_parameters
    self.update_D()
  File "E:\果冻\模型\wgan-gp-anomaly-master\wgan-gp-anomaly-master\models\wgan_gp_model.py", line 100, in update_D
    self.real_data_v = Variable(real_data)
UnboundLocalError: local variable 'real_data' referenced before assignment

**Comment by oyxhust** [comment]
Please use python3. Or directly change the line 97 and 98 to 'real_data = self.input_img.cuda()'.

**Comment by lzzlxxlsz** [comment]
I use the python3,cpu.and has changed the gpu_ids with -1 ,changed the code "real_data = self.input_img.cuda()",but it also turns the same error
