### ISSUE TITLE
数据的选择会对训练产生影响吗

### ISSUE THREAD

**Issue by lzzlxxlsz** [oyxhust/wgan-gp-anomaly#6]
你好，看了原论文之中，用的是医学方面的图片，他们的训练数据集都比较统一，大部分到是相同的结构，所以通过GAN网络之后会生成跟正常图像相似的图像，而异常图像跟正常的图像会有不同，我想问得是，如果自己的数据比较复杂的话，会对训练过程产生影响吗，我的数据背景比较复杂

**Comment by oyxhust** [comment]
会的，我感觉目前这个方法只能做一些比较简单的input

**Comment by lzzlxxlsz** [comment]
您是不是指用GAN网络生成图像，通过比较测试图片跟生成图片（更新噪声来生成跟测试图片相似的图片）的差异来找异常这种方法吗，还是说不同的gan网络会有不同的效果（您使用的是wgan-gp），我看之前有人用DCGAN实现过，使用的数据集是人脸的，但是我运行之后发现测试图片跟最终生成的图片不太像，差异挺大的，但是作者却说效果还好，我又用MNIST数据集做了一下，发现结果也不太好

**Comment by oyxhust** [comment]
这个方法的问题，gan直接从噪声生成的，需要大量数据才能比较好效果，然后现在又要保证生成的质量很好，感觉这个方法只能做简单的异常纹理

**Comment by lzzlxxlsz** [comment]
好的，非常感谢，也就是说如果要使用这个方法，数据集首先要有明显的特征，然后就是数据量的保证是吧。您有一些推荐的对于复杂数据进行异常检测的方法吗
